[phases.install]
# Install Templ and TailwindCSS in the install phase
install = "go install github.com/a-h/templ/cmd/templ@latest && curl -L https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.4/tailwindcss-linux-x64 -o /usr/local/bin/tailwindcss && chmod +x /usr/local/bin/tailwindcss"

# Build static assets (Tailwind and Templ) and Go binary in the build phase
build = "make tailwind-build && make templ-generate && go build -ldflags \"-X main.Environment=production\" -o ./bin/$(APP_NAME) ./cmd/$(APP_NAME)/main.go"

# Start the app with the built Go binary in the start phase
start = "./bin/$(APP_NAME)"

